### ISSUE TITLE
cannot be used with compose?

### ISSUE THREAD

**Issue by Noele** [nasourso/ttt-server#1]
```
version: '3.2'

services:
  ttt:
    image: nasourso/ttt-server
    ports:
      - 192.154.227.72:27015:27015/udp
    privileged: true
    environment:
      - NAME=GoodJobNoele
      - STARTMAP=cs_compound
    volumes:
      - ttt-data:/app
      - ttt-config:/cfg
      - ttt-content:/content

volumes:
 ttt-data:
 ttt-config:
 ttt-content:
```

above is a basic compose config for the container, yet for some reason it fails to start, and when attempted, spits out "You must be connected to a terminal"; I'm assuming this has something to do with backgrounding / ``screen -x`` thats mentioned in the git readme.

**Comment by nasourso** [comment]
It is important to start the console with stdin_open and tty. Code below works fine.

```
version: '3.2'

services:
  ttt:
    image: nasourso/ttt-server
    ports:
      - 27015:27015/udp
    privileged: true
    environment:
      - NAME=GoodJobNoele
      - STARTMAP=cs_compound
    volumes:
      - ttt-data:/app
      - ttt-config:/cfg
      - ttt-content:/content
    stdin_open: true
    tty: true

volumes:
 ttt-data:
 ttt-config:
 ttt-content:
```
